// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using lms_api.Infrastructure;

#nullable disable

namespace lms_api.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    [Migration("20241119095902_Update_Books_Genres")]
    partial class Update_Books_Genres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("lms_api.Application.Books.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CopiesAvailable")
                        .HasColumnType("integer");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "F. Scott Fitzgerald",
                            CopiesAvailable = 5,
                            Genre = "Fiction",
                            ISBN = "9780743273565",
                            PublishedDate = new DateTime(1925, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Great Gatsby"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Harper Lee",
                            CopiesAvailable = 3,
                            Genre = "Fiction",
                            ISBN = "9780061120084",
                            PublishedDate = new DateTime(1960, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "To Kill a Mockingbird"
                        },
                        new
                        {
                            Id = 3,
                            Author = "George Orwell",
                            CopiesAvailable = 4,
                            Genre = "Romance",
                            ISBN = "9780451524935",
                            PublishedDate = new DateTime(1949, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "1984"
                        },
                        new
                        {
                            Id = 4,
                            Author = "J.R.R. Tolkien",
                            CopiesAvailable = 6,
                            Genre = "Fantasy",
                            ISBN = "9780547928227",
                            PublishedDate = new DateTime(1937, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Hobbit"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Dan Brown",
                            CopiesAvailable = 2,
                            Genre = "Mystery",
                            ISBN = "9780307474278",
                            PublishedDate = new DateTime(2003, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Da Vinci Code"
                        });
                });

            modelBuilder.Entity("lms_api.Application.Borrows.Models.Borrow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("BorrowDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("Borrows");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 1,
                            BorrowDate = new DateTime(2024, 11, 9, 9, 59, 0, 781, DateTimeKind.Utc).AddTicks(426),
                            ReturnDate = new DateTime(2024, 11, 17, 9, 59, 0, 781, DateTimeKind.Utc).AddTicks(433),
                            UserId = 3
                        },
                        new
                        {
                            Id = 2,
                            BookId = 3,
                            BorrowDate = new DateTime(2024, 11, 14, 9, 59, 0, 781, DateTimeKind.Utc).AddTicks(437),
                            UserId = 4
                        });
                });

            modelBuilder.Entity("lms_api.Application.Reservations.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ReservationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 2,
                            ExpirationDate = new DateTime(2024, 11, 20, 9, 59, 0, 781, DateTimeKind.Utc).AddTicks(453),
                            ReservationDate = new DateTime(2024, 11, 18, 9, 59, 0, 781, DateTimeKind.Utc).AddTicks(452),
                            UserId = 3
                        },
                        new
                        {
                            Id = 2,
                            BookId = 4,
                            ExpirationDate = new DateTime(2024, 11, 20, 3, 59, 0, 781, DateTimeKind.Utc).AddTicks(455),
                            ReservationDate = new DateTime(2024, 11, 18, 3, 59, 0, 781, DateTimeKind.Utc).AddTicks(454),
                            UserId = 4
                        });
                });

            modelBuilder.Entity("lms_api.Application.Users.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@library.com",
                            PasswordHash = "3eb3fe66b31e3b4d10fa70b5cad49c7112294af6ae4e476a1c405155d45aa121",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "librarian@library.com",
                            PasswordHash = "ef89959c1d160e8c22b09bb7aef5c1397ea5e9aa34b12d505762436fc318ad51",
                            Role = "Librarian",
                            Username = "librarian"
                        },
                        new
                        {
                            Id = 3,
                            Email = "reader1@library.com",
                            PasswordHash = "6282a01621c5b8d19e2ba478809b23ac973f1b482656ad9bb35a8c6ae9033070",
                            Role = "Reader",
                            Username = "reader1"
                        },
                        new
                        {
                            Id = 4,
                            Email = "reader2@library.com",
                            PasswordHash = "ed230349cca678ddd4457631e26d8d44a44e599191c619a352b5ef7d1f8c6a46",
                            Role = "Reader",
                            Username = "reader2"
                        });
                });

            modelBuilder.Entity("lms_api.Application.Borrows.Models.Borrow", b =>
                {
                    b.HasOne("lms_api.Application.Books.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("lms_api.Application.Users.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("lms_api.Application.Reservations.Models.Reservation", b =>
                {
                    b.HasOne("lms_api.Application.Books.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("lms_api.Application.Users.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
